### ISSUE TITLE
Emby parser problem?

### ISSUE THREAD

**Issue by espilioto** [crowdsecurity/hub#421]
Tried installing the Emby collection but something seems to be going wrong;

The logs do get recognised but remain unparsed:
![image](https://user-images.githubusercontent.com/8510006/160794338-31618751-b852-492a-a02f-4d9b79ce8122.png)

Running explain produces this:
![image](https://user-images.githubusercontent.com/8510006/160794117-080f8b1b-37ee-408d-b35e-f34dc7602dc2.png)

Emby log output:
```
2022-03-30 11:52:52.545 Error UserManager: Error authenticating with provider Default
	*** Error Report ***
	Version: 4.6.7.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.0-105-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04)) #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022
	Framework: .NET Core 3.1.21
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: Invalid username or password.
	   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
	   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: System.Threading.Tasks.Task 1[MediaBrowser.Controller.Authentication.ProviderAuthenticationResult] Authenticate(System.String, System.String, MediaBrowser.Controller.Entities.User)
	
2022-03-30 11:52:52.546 Info HttpClient: POST https://connect.emby.media/service/user/authenticate
2022-03-30 11:52:53.065 Warn Server: AUTH-ERROR: 172.xx.xxx.77 - Invalid username or password entered.
2022-03-30 11:52:53.065 Error Server: Invalid username or password entered.
2022-03-30 11:52:53.066 Info Server: http/1.1 Response 401 to 172.xx.xxx.77. Time: 525ms. http://xxx.xxx.xxx/Users/authenticatebyname?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Firefox%20Android&X-Emby-Device-Id=0d299276-fff5-472c-8468-2fc0d62114fa&X-Emby-Client-Version=4.6.7.0
```
@LePresidente Any ideas? :D

**Comment by LePresidente** [comment]
Not sure actually just tested my side and it is working, what is your aqcuis.yml entry for emby?

**Comment by LePresidente** [comment]
Not sure actually just tested my side and it is working, what is your aqcuis.yml entry for emby?

**Comment by LePresidente** [comment]
this is what i would expect to see
```
# cscli explain --log "2022-03-30 11:52:53.065 Warn Server: AUTH-ERROR: 127.0.0.1 - Invalid username or password entered." --type emby
line: 2022-03-30 11:52:53.065 Warn Server: AUTH-ERROR: 127.0.0.1 - Invalid username or password entered.
        ├ s00-raw
        |       ├ 🔴 crowdsecurity/docker-logs
        |       ├ 🟢 crowdsecurity/non-syslog (first_parser)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       ├ 🔴 LePresidente/authelia-logs
        |       └ 🟢 LePresidente/emby-logs (+5 ~2)
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
        |       ├ 🟢 crowdsecurity/geoip-enrich (+9)
        |       ├ 🔴 crowdsecurity/http-logs
        |       └ 🟢 crowdsecurity/whitelists (~2 [whitelisted])
        └-------- parser failure 🔴
 ```

**Comment by espilioto** [comment]
Hmm, weird.
Here is my aqcuis.yml  entry, just copied from the collection:
```
---
filenames:
 - /var/log/embyserver.txt
labels:
  type: Emby
```

The file is correctly mounted of course.

**Comment by LePresidente** [comment]
looks right, can you make sure your hub is updated so `cscli hub update && cscli hub upgrade` also give the output from `cscli parsers inspect LePresidente/emby-logs`

**Comment by espilioto** [comment]
The hub is updated.
Here is the output:

```
time="31-03-2022 11:52:04 AM" level=info msg="Ignoring file /etc/crowdsec/hub/collections/LePresidente/emby.yml of type collections"
type: parsers
stage: s01-parse
name: LePresidente/emby-logs
filename: emby-logs.yaml
description: Parse emby logs
author: LePresidente
belongs_to_collections:
- LePresidente/emby
remote_path: parsers/s01-parse/LePresidente/emby-logs.yaml
version: "0.2"
local_path: /etc/crowdsec/parsers/s01-parse/emby-logs.yaml
localversion: "0.2"
localhash: a059a5f6bd938262e7775f158a6a4fe0902ae44e0f4d853285613553be7ea236
installed: true
downloaded: true
uptodate: true
tainted: false
local: false

Current metrics :

```

**Comment by LePresidente** [comment]
Check your log location again in aqcuis.yaml also make sure the type does match since the parser is not being loaded for the file 

This should of been at the bottom of your previous inspect command
```
Current metrics : 

 - (Parser) LePresidente/emby-logs: 
+------------------------------------+------+--------+----------+
|              PARSERS               | HITS | PARSED | UNPARSED |
+------------------------------------+------+--------+----------+
| file:/var/logs/emby/embyserver.txt |   86 |      1 |       85 |
+------------------------------------+------+--------+----------+
```

my aqcuis.yml file

```
filenames:
  - /var/logs/emby/embyserver*txt
labels:
  type: emby
```

**Comment by espilioto** [comment]
Here's mine:
```
filenames:
  - /var/log/traefik/*
labels:
  type: traefik
---
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
filenames:
 - /var/log/emby/embyserver*txt
labels:
  type: emby
```

**Comment by LePresidente** [comment]
crowdsec only starts parsing when new lines are added, so first go to emby and login/fail login then run inspect again

**Comment by espilioto** [comment]
Yup, yup, yup.
Dammit, it didn't cross my mind.

Thanks for the help man! ❤️
