### ISSUE TITLE
Jellyfin parser

### ISSUE THREAD

**Issue by a1ad** [crowdsecurity/hub#651]
Hi guys and @LePresidente (Emby parser dev),

How hard is it to create a Jellyfin parser?

The logs are in a file format like this: log_20230212.log with the relevant auth data like this:

invalid user:
```
[2023-02-12 12:16:05.728 +01:00] [ERR] [79] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2023-02-12 12:16:05.729 +01:00] [INF] [79] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "tim" has been denied (IP: "1.1.1.1").
[2023-02-12 12:16:05.730 +01:00] [ERR] [79] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".
```
User ok, but invalid password:

```
[2023-02-12 12:17:17.673 +01:00] [ERR] [66] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Invalid username or password
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2023-02-12 12:17:17.684 +01:00] [INF] [66] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "jeroen" has been denied (IP: "1.1.1.1").
[2023-02-12 12:17:17.685 +01:00] [ERR] [66] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".
```

Is it possible to create a acquis file with a log file that changes his name every day? Are datetime variables even possible?

On my installation there are 3 log files, so today they are like this:

log_20230210.log
log_20230211.log
log_20230212.log

So maybe we can add log_*.log to the acquis file?

**Comment by a1ad** [comment]
I am trying to create a grok pattern, but failed. Loz is helping me out on Discord. So far, iv come up with this pattern:

```pattern: '\[%{TIMESTAMP_ISO8601:timestamp}\].*Authentication request for "%{DATA:user}" has been denied \(IP: "%{IP:source_ip}"\)\.$'```
And 
pattern_syntax:
```
  TIMESTAMP_WORKAROUND: '%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:%{MINUTE}:%{SECOND}\.%{INT:milliseconds}[T ]%{ISO8601_TIMEZONE}'
nodes:
  - grok:
      pattern: '\[%{TIMESTAMP_WORKAROUND:timestamp}\].*Authentication request for "%{DATA:username}" has been denied \(IP: "%{IP:source_ip}"\)'
```
I am open for helping hands since its the first time in creating such a pattern.
